---
- name: Device42 cihazlarını çek ve dosyaya kaydet
  hosts: localhost
  gather_facts: false

  vars:
    # AWX Extra Vars üzerinden de geçirebilirsiniz
    device42_api_url: "https://213.153.197.248:8585/api/1.0/devices/all"
    device42_auth_header: "Basic YWRtaW46QWExMjM0NTYu."
    # chunk_size'ı ihtiyacınıza göre ayarlayın
    chunk_size: 1

  tasks:
    - name: Device42'den cihazları çek
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        headers:
          Authorization: "{{ device42_auth_header }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: device42_response

    - name: Cihaz listesini ayıkla
      set_fact:
        devices: "{{ device42_response.json.Devices | default(device42_response.json.devices) }}"

    - name: Cihazları dosyaya kaydet
      copy:
        content: "{{ devices | to_nice_json }}"
        dest: "./device42_devices.json"

    - name: Split devices into chunks of size {{ chunk_size }}
      set_fact:
        device_chunks: "{{ devices | batch(chunk_size, []) }}"

    - name: Show how many chunks were created
      debug:
        msg: "{{ device_chunks | length }} chunks created."

    - name: Display each chunk individually
      debug:
        var: item
      loop: "{{ device_chunks }}"
      loop_control:
        index_var: idx
        label: "devices_chunk_{{ idx+1 }}"
