# fetch-smax-token.yaml
---
- name: Fetch SMAX auth token
  hosts: localhost
  gather_facts: false

  vars:
    # Prompt on Launch ile Extra Vars olarak girin:
    # smax_token_url: "https://destek.kafein.com.tr/auth/authentication-endpoint/authenticate/token?TENANTID=669866050"
    # smax_user:       "duosis.admin"
    # smax_pass:       "duosisITSM.25"

  tasks:
    - name: 1) Get SMAX token via POST
      uri:
        url: "{{ smax_token_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ { 'Login': smax_user, 'Password': smax_pass } | to_json }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: auth_resp

    - name: 2) Expose SMAX_AUTH_TOKEN as workflow fact
      set_stats:
        scoreboard: global
        data:
          smax_cookie: "{{ 'SMAX_AUTH_TOKEN=' + (auth_resp.content | from_json).token }}"
