---
- name: Fetch SMAX auth token
  hosts: localhost
  gather_facts: false

  vars:
    smax_token_url: "https://destek.kafein.com.tr/auth/authentication-endpoint/authenticate/token?TENANTID=669866050"
    smax_user: "duosis.admin"
    smax_pass: "duosisITSM.25"

  tasks:
    - name: 1) Get SMAX token
      uri:
        url: "{{ smax_token_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ { 'Login': smax_user, 'Password': smax_pass } | to_json }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: auth_resp

    - name: 2) Parse token out of response
      set_fact:
        smax_cookie: "SMAX_AUTH_TOKEN={{ (auth_resp.content | from_json).token }}"

    - name: 3) Expose smax_cookie to workflow
      set_stats:
        data:
          smax_cookie: "{{ smax_cookie }}"
