---
- name: Fetch SMAX auth token and print it
  hosts: localhost
  gather_facts: false

  vars:
    # Extra Vars olarak Launch ekranından girin (ya da doğrudan buraya sabitleyin)
    smax_token_url: "https://destek.kafein.com.tr/auth/authentication-endpoint/authenticate/token?TENANTID=669866050"
    smax_user:       "duosis.admin"
    smax_pass:       "duosisITSM.25"

  tasks:
    - name: 1) Request SMAX token
      uri:
        url: "{{ smax_token_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ { 'Login': smax_user, 'Password': smax_pass } | to_json }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: auth_resp

    - name: 2) Parse token from response
      set_fact:
        smax_token: "{{ (auth_resp.content | from_json).token }}"

    - name: 3) Show the token in output
      debug:
        msg:
          - "Fetched SMAX token:"
          - "{{ smax_token }}"
