---
- name: Send Device42 devices to SMAX (via dynamic token)
  hosts: localhost
  gather_facts: false

  vars:
    # Device42 bağlantı bilgileri
    device42_api_url: "https://213.153.197.248:8585/api/1.0/devices/all"
    device42_auth_header: "Basic YWRtaW46QWExMjM0NTYu."
    chunk_size: 1

    # SMAX endpoint, ama cookie değeri workflow’dan gelecek
    smax_api_url: "https://destek.kafein.com.tr/rest/669866050/ems/bulk"
    smax_cookie: "{{ smax_cookie }}"

  tasks:
    - name: 1) Retrieve all devices from Device42
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        headers:
          Authorization: "{{ device42_auth_header }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: device42_response

    - name: 2) Parse devices list from response JSON
      set_fact:
        devices: "{{ device42_response.json.Devices | default(device42_response.json.devices) }}"

    - name: 3) Split devices into chunks of size {{ chunk_size }}
      set_fact:
        device_chunks: "{{ devices | batch(chunk_size, []) }}"

    - name: 4) Show how many chunks were created
      debug:
        msg: "{{ device_chunks | length }} chunks created."

    - name: 5) Loop over each chunk and send to SMAX
      vars:
        smax_payload: |
          {
            "entities": [
              {% for device in item %}
              {
                "entity_type": "Device",
                "properties": {
                  "HostName": "{{ device.name | default('') }}",
                  "MemorySize": {{ device.ram | default(0) }},
                  "AssetTag": "{{ device.asset_no | default('') }}",
                  "Cpus": "{{ {'Cpu':[{
                    'CpuType':'',
                    'CpuVendor':'',
                    'CpuClockSpeed': (device.cpuspeed|default(0)) | string,
                    'CpuId':'',
                    'CpuCoreNumber': (device.cpucore|default(device.cpucount|default(0)))
                  }]} | to_json }}",
                  "IPAddress": "{% if device.ip_addresses is defined and device.ip_addresses|length > 0 %}{{ device.ip_addresses[0].ip }}{% else %}{% endif %}",
                  "SerialNo": "{{ device.serial_no | default('') }}",
                  "OSName": "{{ device.os | default('') }}",
                  "OSVersion": "{{ device.osver | default('') }}",
                  "Category": "{{ device.category | default('') }}"
                }
              }{% if not loop.last %},{% endif %}
              {% endfor %}
            ],
            "operation": "CREATE"
          }
      uri:
        url: "{{ smax_api_url }}"
        method: POST
        headers:
          Cookie: "{{ smax_cookie }}"
          Content-Type: "application/json"
        body: "{{ smax_payload }}"
        status_code: 200,201,202
        validate_certs: no
      loop: "{{ device_chunks }}"
      loop_control:
        index_var: idx
        label: "chunk_{{ idx }}"
      register: smax_responses

    - name: 6) Show SMAX responses for each chunk
      debug:
        var: item
      loop: "{{ smax_responses.results }}"
      loop_control:
        index_var: rsp_idx
        label: "response_{{ rsp_idx }}"
