---
- name: Webhook ile gelen alert'e göre belirtilen dizindeki dosyaları temizle
  hosts: localhost
  gather_facts: false
  vars:
    # Silinecek dizin yolu - AWX'den değiştirilebilir
    target_directory: "{{ target_directory | default('/test') }}"
  tasks:
    - name: Webhook payload'ını debug et
      debug:
        msg: 
          - "Event: {{ event_name | default('Bilinmiyor') }}"
          - "Host: {{ host_name | default('Bilinmiyor') }}"
          - "IP: {{ host_ip | default('Bilinmiyor') }}"
          - "Hedef Dizin: {{ target_directory }}"

    - name: Host'un variable'larını al
      set_fact:
        target_host: "{{ host_name }}"
        server_ip: "{{ host_ip }}"
        server_username: "duosis"
        server_password: "Qwerasdf1234"
        ssh_port: "{{ ssh_port | default(22) }}"

    - name: Hedef sunucuya bağlantıyı test et
      ping:
      delegate_to: "{{ target_host }}"
      vars:
        ansible_host: "{{ server_ip }}"
        ansible_user: "{{ server_username }}"
        ansible_password: "{{ server_password }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=30'

    - name: Hedef sunucuya bağlan ve belirtilen dizindeki dosyaları temizle
      block:
        - name: Hedef dizindeki dosyaları listele
          file:
            path: "{{ target_directory }}"
            state: directory
          register: dir_info

        - name: Hedef dizindeki tüm dosyaları sil
          file:
            path: "{{ item }}"
            state: absent
          loop: "{{ dir_files.files }}"
          vars:
            dir_files: "{{ lookup('fileglob', target_directory + '/*', wantlist=True) | map('basename') | list }}"
          when: dir_files | length > 0

        - name: Hedef dizindeki tüm dizinleri sil
          file:
            path: "{{ item }}"
            state: absent
          loop: "{{ dir_dirs.dirs }}"
          vars:
            dir_dirs: "{{ lookup('fileglob', target_directory + '/*/', wantlist=True) | map('basename') | list }}"
          when: dir_dirs | length > 0

        - name: Temizlik sonrası hedef dizini kontrol et
          command: ls -la "{{ target_directory }}"
          register: cleanup_result

        - name: Temizlik sonucunu raporla
          debug:
            msg: 
              - "Temizlik tamamlandı!"
              - "Hedef dizin: {{ target_directory }}"
              - "Kalan dosyalar: {{ cleanup_result.stdout_lines }}"

      delegate_to: "{{ target_host }}"
      become: yes
      become_user: root
      vars:
        ansible_host: "{{ server_ip }}"
        ansible_user: "{{ server_username }}"
        ansible_password: "{{ server_password }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=30' 