---
- name: Device42'dan cihaz çek ve dbag inventory'sine ekle
  hosts: localhost
  gather_facts: false
  vars:
    device42_api_url: "https://device42.example.com/api/1.0/devices/all/"
    device42_username: "admin"
    device42_password: "Aa123456."
    awx_api_url: "https://awx.example.com/api/v2"
    awx_token: "4536bvXZZS4G3yV0clW2MLGblBsZti"
    dbag_inventory_id: 5  # dbag inventory'nin id'si (AWX'den öğrenebilirsin)
  tasks:
    - name: Device42'dan cihazları çek
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        user: "{{ device42_username }}"
        password: "{{ device42_password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: no
      register: d42_response

    - name: dbag custom field'ı olan cihazları ve ip'lerini bul
      set_fact:
        dbag_hosts: >-
          {{
            d42_response.json.Devices
            | selectattr('custom_fields', 'defined')
            | selectattr('custom_fields', 'select', lambda fields: fields | selectattr('key', 'search', '^dbag', ignorecase=True) | list | length > 0)
            | map(attribute='ip_addresses')
            | map('map', attribute='ip')
            | sum(start=[])
            | unique
          }}

    - name: dbag inventory'sine host ekle
      uri:
        url: "{{ awx_api_url }}/inventories/{{ dbag_inventory_id }}/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ item }}"
          inventory: "{{ dbag_inventory_id }}"
        status_code: [201, 409]  # 409 = zaten var
        validate_certs: no
      loop: "{{ dbag_hosts }}"
      when: dbag_hosts | length > 0 