---
- name: Device42'dan cihaz çek ve dbag inventory'sine ekle
  hosts: localhost
  gather_facts: false
  vars:
    # Bu değişkenler AWX'den gelecek
    device42_api_url: "{{ device42_api_url }}"
    device42_username: "{{ device42_username }}"
    device42_password: "{{ device42_password }}"
    awx_api_url: "{{ awx_api_url }}"
    awx_token: "{{ awx_token }}"
    dbag_inventory_id: "{{ dbag_inventory_id }}"
  tasks:
    - name: Device42'dan cihazları çek
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        user: "{{ device42_username }}"
        password: "{{ device42_password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: no
      register: d42_response

    - name: dbag custom field'ı olan cihazları ve ip'lerini bul
      set_fact:
        dbag_hosts: >-
          {{
            d42_response.json.Devices
            | selectattr('custom_fields', 'defined')
            | selectattr('custom_fields', 'select', lambda fields: fields | selectattr('key', 'search', '^dbag', ignorecase=True) | list | length > 0)
            | map(attribute='ip_addresses')
            | map('map', attribute='ip')
            | sum(start=[])
            | unique
          }}

    - name: dbag inventory'sine host ekle
      uri:
        url: "{{ awx_api_url }}/inventories/{{ dbag_inventory_id }}/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ item }}"
          inventory: "{{ dbag_inventory_id }}"
        status_code: [201, 409]  # 409 = zaten var
        validate_certs: no
      loop: "{{ dbag_hosts }}"
      when: dbag_hosts | length > 0 