---
- name: D42 ve SMAX cihazlarını karşılaştır
  hosts: localhost
  gather_facts: false

  vars:
    # D42 için
    device42_api_url: "{{ device42_api_url }}"  # AWX Extra Vars ile gelmeli
    device42_auth_header: "{{ device42_auth_header }}"  # AWX Extra Vars ile gelmeli
    # SMAX için
    smax_token_url: "{{ smax_token_url }}"  # AWX Extra Vars ile gelmeli
    smax_user: "{{ smax_user }}"  # AWX Extra Vars ile gelmeli
    smax_pass: "{{ smax_pass }}"  # AWX Extra Vars ile gelmeli
    smax_api_url: "{{ smax_api_url }}"  # AWX Extra Vars ile gelmeli
    smax_layout: "LastUpdateTime,DisplayLabel,Description,Cpus,MemorySize,RunningSoftwares,D42id_c,IpAddresses,OsName,DiskDevices,NetworkCards"
    smax_tenantid: "669866050"

  tasks:
    - name: D42 cihazlarını çek
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        headers:
          Authorization: "{{ device42_auth_header }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: d42_response

    - name: D42 cihaz listesini çıkar
      set_fact:
        d42_devices: "{{ d42_response.json.Devices | default(d42_response.json.devices) }}"

    - name: SMAX token al
      uri:
        url: "{{ smax_token_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ { 'Login': smax_user, 'Password': smax_pass } | to_json }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: smax_token_response

    - name: SMAX token'ı çıkar
      set_fact:
        smax_token: "{{ smax_token_response.content }}"

    - name: SMAX token response'unu göster
      debug:
        var: smax_token_response

    - name: SMAX cihazlarını çek
      uri:
        url: "{{ smax_api_url }}?layout={{ smax_layout | urlencode }}"
        method: GET
        headers:
          Cookie: "SMAX_AUTH_TOKEN={{ smax_token }}; TENANTID={{ smax_tenantid }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: smax_response

    - name: SMAX cihaz çekme response'unu göster
      debug:
        var: smax_response

    - name: SMAX cihaz çekme response'unun json'unu göster
      debug:
        var: smax_response.json

    - name: SMAX cihaz listesini çıkar
      set_fact:
        smax_devices: "{{ smax_response.json.entities | default([]) }}"

    - name: SMAX cihazlarının properties alanlarını göster
      debug:
        msg: "{{ item.properties }}"
      loop: "{{ smax_devices }}"

    - name: D42 cihazlarını SMAX properties formatına dönüştür
      set_fact:
        d42_devices_properties: >-
          {{ d42_devices | map('combine', {'properties': {
            'D42id_c': (item.device_id | string),
            'DisplayLabel': item.name | default(''),
            'MemorySize': item.ram | default(''),
            'OsName': item.os | default(''),
            'IpAddresses': item.ip_addresses | default([]),
            'Cpus': item.cpucount | default(''),
            'DiskDevices': item.hdd_details | default([]),
            'NetworkCards': item.mac_addresses | default([])
          }}) | list }}
      loop: "{{ d42_devices }}"
      loop_control:
        loop_var: item

    - name: D42 ve SMAX cihazlarını D42id_c/id üzerinden eşleştir (properties formatı ile)
      set_fact:
        d42_ids: "{{ d42_devices_properties | map(attribute='properties') | map(attribute='D42id_c') | select('string') | list }}"
        smax_ids: "{{ smax_devices | map(attribute='properties') | map(attribute='D42id_c') | select('string') | list }}"

    - name: D42'de olup SMAX'de olmayan cihazları bul (Yeni Yazdırılacak Cihazlar)
      set_fact:
        yeni_yazdirilacak_cihazlar: >-
          {{ d42_devices_properties | selectattr('properties.D42id_c', 'in', (d42_ids | difference(smax_ids))) | list }}

    - name: İki tarafta da olup farklı olan cihazları bul (Güncellenecek Cihazlar)
      set_fact:
        guncellenecek_cihazlar: >-
          {{ d42_devices_properties | selectattr('properties.D42id_c', 'in', (d42_ids | intersect(smax_ids))) | list }}

    - name: Sonuçları göster
      debug:
        msg: |
          Yeni Yazdırılacak Cihazlar (D42'de olup SMAX'de olmayanlar):
          {{ yeni_yazdirilacak_cihazlar | map(attribute='properties.DisplayLabel') | list }}

          Güncellenecek Cihazlar (İki tarafta da olup farklı olanlar):
          {{ guncellenecek_cihazlar | map(attribute='properties.DisplayLabel') | list }}
