---
- name: D42 ve SMAX cihazlarını karşılaştır
  hosts: localhost
  gather_facts: false

  vars:
    # D42 için
    device42_api_url: "{{ device42_api_url }}"  # AWX Extra Vars ile gelmeli
    device42_auth_header: "{{ device42_auth_header }}"  # AWX Extra Vars ile gelmeli
    # SMAX için
    smax_token_url: "{{ smax_token_url }}"  # AWX Extra Vars ile gelmeli
    smax_user: "{{ smax_user }}"  # AWX Extra Vars ile gelmeli
    smax_pass: "{{ smax_pass }}"  # AWX Extra Vars ile gelmeli
    smax_api_url: "{{ smax_api_url }}"  # AWX Extra Vars ile gelmeli
    smax_layout: "LastUpdateTime,DisplayLabel,Description,Cpus,MemorySize,RunningSoftwares,D42id_c,IpAddresses,OsName,DiskDevices,NetworkCards"
    smax_tenantid: "669866050"

  tasks:
    - name: D42 cihazlarını çek
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        headers:
          Authorization: "{{ device42_auth_header }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: d42_response

    - name: D42 cihaz listesini çıkar
      set_fact:
        d42_devices: "{{ d42_response.json.Devices | default(d42_response.json.devices) }}"

    - name: SMAX token al
      uri:
        url: "{{ smax_token_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ { 'Login': smax_user, 'Password': smax_pass } | to_json }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: smax_token_response

    - name: SMAX token'ı çıkar
      set_fact:
        smax_token: "{{ smax_token_response.content }}"

    - name: SMAX token response'unu göster
      debug:
        var: smax_token_response

    - name: SMAX cihazlarını çek
      uri:
        url: "{{ smax_api_url }}?layout={{ smax_layout | urlencode }}"
        method: GET
        headers:
          Cookie: "SMAX_AUTH_TOKEN={{ smax_token }}; TENANTID={{ smax_tenantid }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: smax_response

    - name: SMAX cihaz çekme response'unu göster
      debug:
        var: smax_response

    - name: SMAX cihaz çekme response'unun json'unu göster
      debug:
        var: smax_response.json

    - name: SMAX cihaz listesini çıkar
      set_fact:
        smax_devices: "{{ smax_response.json.entities | default([]) }}"

    - name: SMAX cihazlarını Device42 formatına dönüştür
      set_fact:
        smax_devices_mapped: []

    - name: SMAX cihazlarını Device42 formatına güvenli şekilde dönüştür (her cihaz için)
      set_fact:
        smax_devices_mapped: "{{ smax_devices_mapped + [ mapped_device ] }}"
      vars:
        nc_decoded: >-
          {{ (item.properties.NetworkCards | from_json) if (item.properties.NetworkCards is defined and item.properties.NetworkCards|length > 0) else [] }}
        mapped_device:
          device_id: "{{ item.properties.D42id_c | default('') }}"
          name: "{{ item.properties.DisplayLabel | default('') }}"
          manufacturer: "{{ item.properties.Vendor | default('') }}"
          hw_model: "{{ item.properties.Model | default('') }}"
          ip_addresses: >-
            {{ (item.properties.IpAddresses | from_json) if (item.properties.IpAddresses is defined and item.properties.IpAddresses|length > 0) else [] }}
          mac_addresses: >-
            {{ nc_decoded if nc_decoded is iterable and nc_decoded is not string else [] | map(attribute='MacAddress') | list }}
          cpus: >-
            {{ (item.properties.Cpus | from_json) if (item.properties.Cpus is defined and item.properties.Cpus|length > 0) else [] }}
          hdd_details: >-
            {{ (item.properties.DiskDevices | from_json) if (item.properties.DiskDevices is defined and item.properties.DiskDevices|length > 0) else [] }}
          memory: "{{ item.properties.MemorySize | default('') }}"
          os: "{{ item.properties.OsName | default('') }}"
      loop: "{{ smax_devices }}"

    - name: SMAX cihazlarının Device42 formatındaki halini göster
      debug:
        var: smax_devices_mapped

    - name: Device42'den gelen cihaz adlarını göster
      debug:
        msg: "{{ d42_devices | map(attribute='name') | list }}"

    - name: SMAX'ten gelen cihaz adlarını göster
      debug:
        msg: "{{ smax_devices_mapped | map(attribute='name') | list }}"

    - name: D42 ve SMAX cihazlarını isim (name) üzerinden eşleştir
      set_fact:
        d42_names: "{{ d42_devices | map(attribute='name') | select('string') | list }}"
        smax_names: "{{ smax_devices_mapped | map(attribute='name') | select('string') | list }}"

    - name: D42'de olup SMAX'de olmayan cihazları bul (Yeni Yazdırılacak Cihazlar)
      set_fact:
        yeni_yazdirilacak_cihazlar: >-
          {{ d42_devices | selectattr('name', 'defined') | selectattr('name', 'in', (d42_names | difference(smax_names))) | list }}

    - name: İki tarafta da olup farklı olan cihazları bul (Güncellenecek Cihazlar)
      set_fact:
        guncellenecek_cihazlar: >-
          {{ d42_devices | selectattr('name', 'in', (d42_names | intersect(smax_names))) | selectattr('name', 'defined') | list }}

    - name: Güncellenecek cihazlarda farklı olan alanları göster
      vars:
        smax_dict: "{{ dict(smax_devices_mapped | map(attribute='name') | zip(smax_devices_mapped)) }}"
      debug:
        msg: >-
          {% set d42 = item %}
          {% set smax = smax_dict[d42.name] %}
          {% set farklar = [] %}
          {% for alan in ['memory', 'serial_no', 'uuid', 'name', 'device_id', 'os', 'ip_addresses', 'cpus', 'hdd_details', 'mac_addresses', 'manufacturer', 'hw_model', 'service_level'] %}
            {% if d42.get(alan) != smax.get(alan) %}
              {% set d42_val = d42.get(alan) %}
              {% set smax_val = smax.get(alan) %}
              {% if d42_val is mapping or d42_val is sequence %}
                {% set d42_val = d42_val | to_nice_json %}
              {% endif %}
              {% if smax_val is mapping or smax_val is sequence %}
                {% set smax_val = smax_val | to_nice_json %}
              {% endif %}
              {% set _ = farklar.append('  - ' ~ alan ~ ':\n      D42: ' ~ d42_val|string ~ '\n      SMAX: ' ~ smax_val|string) %}
            {% endif %}
          {% endfor %}
          {{ d42.name }} için farklı alanlar:\n{{ farklar | join('\n') if farklar else '  YOK' }}
      loop: "{{ guncellenecek_cihazlar }}"

    - name: Sonuçları göster
      debug:
        msg: |
          Yeni Yazdırılacak Cihazlar (D42'de olup SMAX'de olmayanlar):
          {{ yeni_yazdirilacak_cihazlar | map(attribute='name') | list }}

          Güncellenecek Cihazlar (İki tarafta da olup farklı olanlar):
          {{ guncellenecek_cihazlar | map(attribute='name') | list }}
