---
- name: Fetch Device42 devices and prepare for SMAX
  hosts: localhost
  gather_facts: false

  vars:
    device42_api_url: "{{ device42_api_url }}"  # AWX Extra Vars input
    device42_auth_header: "{{ device42_auth_header }}"  # AWX Extra Vars input
    chunk_size: "{{ chunk_size | default(1) }}"  # AWX Extra Vars input, default 1

  tasks:
    - name: Fetch devices from Device42
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        headers:
          Authorization: "{{ device42_auth_header }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: device42_response

    - name: Extract device list
      set_fact:
        devices: "{{ device42_response.json.Devices | default(device42_response.json.devices) }}"

    - name: Split devices into chunks
      set_fact:
        device_chunks: "{{ devices | batch(chunk_size | int, []) }}"

    - name: Show number of chunks created
      debug:
        msg: "{{ device_chunks | length }} chunks created."

    - name: Display each chunk
      debug:
        var: item
      loop: "{{ device_chunks }}"
      loop_control:
        index_var: idx
        label: "devices_chunk_{{ idx+1 }}"

    - name: Output devices data for next playbook
      debug:
        msg: "Devices data ready for SMAX integration"

    - name: Display devices data
      debug:
        var: devices
      when: devices is defined

    - name: Set fact for devices count
      set_fact:
        total_devices: "{{ devices | length }}"

    - name: Show summary
      debug:
        msg: "Total {{ total_devices }} devices fetched from Device42 and ready for SMAX integration" 