# send-to-smax.yaml
---
- name: Insert Device42 devices into SMAX
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Fetch devices from Device42
      uri:
        url: "{{ device42_api_url }}"
        method: GET
        headers:
          Authorization: "{{ device42_auth_header }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: device42_response
      when: device42_api_url is defined and device42_auth_header is defined

    - name: Fail if Device42 variables are not provided
      fail:
        msg: "device42_api_url and device42_auth_header must be provided in AWX Extra Vars"
      when: device42_api_url is not defined or device42_auth_header is not defined

    - name: Extract device list
      set_fact:
        devices: "{{ device42_response.json.Devices | default(device42_response.json.devices) }}"
      when: device42_response is defined

    - name: Split devices into chunks
      set_fact:
        device_chunks: "{{ devices | batch((chunk_size | default(1)) | int, []) }}"
      when: devices is defined

    - name: Show number of chunks created
      debug:
        msg: "{{ device_chunks | length }} chunks created for SMAX processing."
      when: device_chunks is defined

    - name: Get SMAX token
      uri:
        url: "{{ smax_token_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ { 'Login': smax_user, 'Password': smax_pass } | to_json }}"
        return_content: yes
        status_code: 200
        validate_certs: no
      register: smax_token_response
      when: smax_token_url is defined and smax_user is defined and smax_pass is defined

    - name: Show SMAX token response for debugging
      debug:
        var: smax_token_response
      when: smax_token_response is defined

    - name: Extract token
      set_fact:
        smax_token: "{{ smax_token_response.content }}"
      when: smax_token_response is defined and smax_token_response.content is defined
      register: token_extraction_result
      ignore_errors: yes

    - name: Show token extraction result
      debug:
        var: token_extraction_result
      when: token_extraction_result is defined

    - name: Fail if token extraction failed
      fail:
        msg: "Failed to extract token from SMAX response. Response content: {{ smax_token_response.content }}"
      when: token_extraction_result is failed

    - name: Send each chunk to SMAX
      vars:
        smax_payload: |
          {
            "entities": [
              {% for device in item %}
              {
                "entity_type": "Device",
                "properties": {
                  "HostName": "{{ device.name | default('') }}",
                  "MemorySize": {{ device.ram | default(0) }},
                  "AssetTag": "{{ device.asset_no | default('') }}",
                  "Cpus": "{{ {'Cpu':[{
                    'CpuType':'',
                    'CpuVendor':'',
                    'CpuClockSpeed': (device.cpuspeed|default(''))|string,
                    'CpuId':'',
                    'CpuCoreNumber': (device.cpucore|default(device.cpucount|default(0)))|string
                  }]} | to_json }}",
                  "IpAddresses": "{{ {'IpAddress':[{'IpValue': (device.ip_addresses[0].ip if device.ip_addresses|length > 0 else ''),'IpType':'','AuthoritativeDNSName':'','RoutingDomain':'','GlobalId':'','Keep':'','Id':''}]} | to_json }}",
                  "SerialNo": "{{ device.serial_no | default('') }}",
                  "OSName": "{{ device.os | default('') }}",
                  "OSVersion": "{{ device.osver | default('') }}",
                  "Category": "{{ device.category | default('') }}",
                  "D42id_c": "{{ device.device_id | default(device.id) | default('') }}"
                }
              }{% if not loop.last %},{% endif %}
              {% endfor %}
            ],
            "operation": "CREATE"
          }
      uri:
        url: "{{ smax_api_url }}"
        method: POST
        headers:
          Cookie: "SMAX_AUTH_TOKEN={{ smax_token }}"
          Content-Type: "application/json"
        body: "{{ smax_payload }}"
        status_code: 200,201,202
        validate_certs: no
      loop: "{{ device_chunks }}"
      loop_control:
        index_var: idx
        label: "chunk_{{ idx }}"
      register: smax_responses
      when: device_chunks is defined and smax_token is defined

    - name: Show SMAX responses
      debug:
        var: item
      loop: "{{ smax_responses.results }}"
      loop_control:
        index_var: rsp_idx
        label: "response_{{ rsp_idx }}"
      when: smax_responses is defined
